#!/bin/sh

# copy startup scripts and set proper flags
sudo cp /usr/local/bin/homegenie/DEBIAN/homegenie /etc/init.d/
sudo chmod +x /etc/init.d/homegenie
sudo cp /usr/local/bin/homegenie/DEBIAN/startup.sh /usr/local/bin/homegenie/
sudo chmod +x /usr/local/bin/homegenie/startup.sh
sudo cp /usr/local/bin/homegenie/DEBIAN/startup_debug.sh /usr/local/bin/homegenie/
sudo chmod +x /usr/local/bin/homegenie/startup_debug.sh
sudo update-rc.d -f homegenie defaults

# start homegenie service
sudo rm -f /usr/local/bin/homegenie/serviceaddress.txt
sudo /etc/init.d/homegenie start

# wait for homegenie service to come up
sleep 1
while [ ! -f /usr/local/bin/homegenie/serviceaddress.txt ]; do sleep 1; echo "."; done
sleep 1
echo "HomeGenie service successfully installed."
while read LINE; do export "$LINE"; done < /usr/local/bin/homegenie/serviceaddress.txt
if [ "$HG_SERVICE_HOST" = "+" ]; then
    HG_SERVICE_HOST="localhost";
fi
echo "You can now browse to http://$HG_SERVICE_HOST:$HG_SERVICE_PORT/ to access HomeGenie web interface."
