#!/bin/sh

# local vars
HG_USER="homegenie"
HOME_FOLDER="/home/$HG_USER"

# add user homegenie
sudo useradd $HG_USER
sudo gpasswd -a $HG_USER dialout
sudo gpasswd -a $HG_USER gpio

# fix folder permissions
sudo chown -R $HG_USER:$HG_USER $HOME_FOLDER

# fix GPIO permissions
#sudo chgrp -R dialout /sys/class/gpio
#sudo chmod -R g+rw /sys/class/gpio

# copy service startup scripts and fix home folder permissions
sudo cp $HOME_FOLDER/DEBIAN/homegenie /etc/init.d/
sudo chown $HG_USER:$HG_USER /etc/init.d/homegenie
sudo chmod +x /etc/init.d/homegenie
sudo cp $HOME_FOLDER/DEBIAN/startup.sh $HOME_FOLDER/
sudo chmod +x $HOME_FOLDER/startup.sh
sudo cp $HOME_FOLDER/DEBIAN/startup_debug.sh $HOME_FOLDER/
sudo chmod +x $HOME_FOLDER/startup_debug.sh
sudo chown -R $HG_USER:$HG_USER $HOME_FOLDER
sudo update-rc.d -f homegenie defaults

# start homegenie service
sudo rm -f $HOME_FOLDER/serviceaddress.txt
sudo /etc/init.d/homegenie start

# wait for homegenie service to come up
sleep 1
while [ ! -f $HOME_FOLDER/serviceaddress.txt ]; do sleep 1; echo "."; done
sleep 1
echo "HomeGenie service successfully installed."
while read LINE; do export "$LINE"; done < $HOME_FOLDER/serviceaddress.txt
if [ "$HG_SERVICE_HOST" = "+" ]; then
    HG_SERVICE_HOST="localhost";
fi
echo "You can now browse to http://$HG_SERVICE_HOST:$HG_SERVICE_PORT/ to access HomeGenie web interface."
