using System;

namespace ZWaveLib.Devices
{
    
    public enum ParameterType
    {
        LEVEL,
        MANUFACTURER_SPECIFIC,
        GENERIC,
        METER_KW_HOUR,
        METER_KVA_HOUR,
        METER_WATT,
        METER_PULSES,
        METER_AC_VOLT,
        METER_AC_CURRENT,
        METER_POWER,
        SENSOR_TEMPERATURE,
        SENSOR_HUMIDITY,
        SENSOR_LUMINANCE,
        SENSOR_MOTION,
        ALARM_DOORWINDOW,
        ALARM_GENERIC,
        ALARM_SMOKE,
        ALARM_CARBONMONOXIDE,
        ALARM_CARBONDIOXIDE,
        ALARM_HEAT,
        ALARM_FLOOD,
        ALARM_TAMPERED,
        CONFIGURATION,
        WAKEUP_INTERVAL,
        WAKEUP_NOTIFY,
        ASSOCIATION,
        BATTERY,
        NODE_INFO,
        MULTIINSTANCE_SWITCH_BINARY_COUNT,
        MULTIINSTANCE_SWITCH_BINARY,
        MULTIINSTANCE_SWITCH_MULTILEVEL_COUNT,
        MULTIINSTANCE_SWITCH_MULTILEVEL,
        MULTIINSTANCE_SENSOR_BINARY_COUNT,
        MULTIINSTANCE_SENSOR_BINARY,
        MULTIINSTANCE_SENSOR_MULTILEVEL_COUNT,
        MULTIINSTANCE_SENSOR_MULTILEVEL,
        THERMOSTAT_FAN_MODE,
        THERMOSTAT_FAN_STATE,
        THERMOSTAT_HEATING,
        THERMOSTAT_MODE,
        THERMOSTAT_OPERATING_STATE,
        THERMOSTAT_SETBACK,
        THERMOSTAT_SETPOINT
    }

}

